#!/usr/bin/ruby

# Given a set of files, will change the names (|pg line) based on the rules in the function
# change_line

# This program is normally called from the change_names.sh script

require 'FileUtils'

# After you have run a script, move these lines to the 'old_change_line' routine
# so there is some history of the changes.

def change_line(line)
  line.gsub!("Claudio Nunes Claudio", "Claudio Nunes")
  line.gsub!("Claudio Nunes Clau", "Claudio Nunes")
  line.gsub!("Claudio Nunes. C", "Claudio Nunes")
  line.gsub!("NUNES Clau", "Claudio Nunes")
  line.gsub!("Fulvio Fantoni G.", "Fulvio Fantoni")
  line.gsub!("fantoni.f", "Fulvio Fantoni")
  line.gsub!("fantoni", "Fulvio Fantoni")
	# An example of the difficulty of changing one name
	# Search the list of ALL names to find the match
  line.gsub!("A Sementa", "Antonio Sementa")
  line.gsub!("A.Sementa", "Antonio Sementa")
  line.gsub!("Sementa A.", "Antonio Sementa")
  line.gsub!("Sementa A", "Antonio Sementa")
  line.gsub!("Sementa. A", "Antonio Sementa")
  line.gsub!("sementa", "Antonio Sementa")
	# Now replace all the 'Sementa' with 'Antonio Sementa'
  line.gsub!("Sementa", "Antonio Sementa")
	# Now we have lots of "Antonio Antonio Sementa"
  line.gsub!("Antonio Antonio Sementa", "Antonio Sementa")

  line.gsub!("Ag Agustin Madala", "Agustin Madala")
  line.gsub!("Ag.Agustin Madala", "Agustin Madala")
  line.gsub!("A. Madala", "Agustin Madala")
  line.gsub!("Madala A.", "Agustin Madala")
	# Must make sure that madala is not part of someone else's name!!
  line.gsub!("madala", "Agustin Madala")
  line.gsub!("Madala", "Agustin Madala")
  line.gsub!("Agustin Agustin Madala", "Agustin Madala")
	
  line.gsub!("Bob Bob Hamman", "Bob Hamman")

  line.gsub!("B Senior", "Brian Senior")
  line.gsub!("BRINK Sjoert", "Sjoert Brink")
  line.gsub!("BRINK Sjoe", "Sjoert Brink")
  line.gsub!("BROCK Sall", "Sally Brock")

  line.gsub!("Helness Tor", "Tor Helness")
  line.gsub!("Helness To", "Tor Helness")
  line.gsub!("Helness T.", "Tor Helness")
  line.gsub!("Helness T", "Tor Helness")
  line.gsub!("Helness.T", "Tor Helness")
  line.gsub!("T. Helness", "Tor Helness")
  line.gsub!("T.Helness", "Tor Helness")
  line.gsub!("TorHelness", "Tor Helness")
  line.gsub!("helness tor", "Tor Helness")
  line.gsub!("helness", "Tor Helness")

  line.gsub!("Versace Alfredo", "Alfredo Versace")
  line.gsub!("Versace Al", "Alfredo Versace")
  line.gsub!("Versace Al", "Alfredo Versace")
  line.gsub!("Versace A.", "Alfredo Versace")
  line.gsub!("Versace. A", "Alfredo Versace")
  line.gsub!("Versace.A", "Alfredo Versace")
  line.gsub!("versace", "Alfredo Versace")
	# Chance all Versace - unique name
  line.gsub!("Versace", "Alfredo Versace")
  line.gsub!("Alfredo Alfredo Versace", "Alfredo Versace")
	# Not quite unique
  line.gsub!("Alfredo Versace L.", "L. Versace")
	return line
end


def old_change_line(line)
  line.gsub!("LEVINE", "Levine")
  line.gsub!("LEVIN", "Levin")
  line.gsub!("J Levin", "Jill Levin")
  line.gsub!("R Levin", "Bobby Levin")
  line.gsub!("R\. Levin", "Bobby Levin")
  line.gsub!("STANSBY", "Stansby")
  line.gsub!("J. Lew Stansby", "Joanna Stansby")
  line.gsub!("L. Lew Stansby", "Joanna Stansby")
  line.gsub!("WOLPERT", "Wolpert")
  line.gsub!("J Wolpert", "Jill Wolpert")
  line.gsub!("LarryCohen", "Larry Cohen")
  line.gsub!("Madala", "Agustin Madala")
  line.gsub!("Agustin Agustin Madala", "Agustin Madala")
  line.gsub!("N Smith", "Nicola Smith")
  line.gsub!("T Helness", "Tor Helness")
  line.gsub!("J\.lall", "Justin Lall")
  line.gsub!("Hamman", "Bob Hamman")
  line.gsub!("DUBOIN", "DUBOIN")
  line.gsub!("BOCCHI", "BOCCHI")
  line.gsub!("passell", "Mike Passell")
  line.gsub!("MAHMOOD Zia", "Zia")
  line.gsub!("MAHMOOD Zi", "Zia")
  line.gsub!("passell", "Mike Passell")
  line.gsub!("VERSACE Al", "Alfredo Versace")
  line.gsub!("SEMENTA An", "Antonio Sementa")
  line.gsub!("Duboin Gio", "Giorgio Duboin")
  line.gsub!("DUBOIN G\.", "Giorgio Duboin")
  line.gsub!("VERSACE", "Versace")
  line.gsub!("LAURIA", "Lauria")
  line.gsub!("WOLFF", "Wolff")
  line.gsub!("MORSE", "Morse")
  line.gsub!("BATES", "Bates")
  line.gsub!("CAYNE", "Jimmy Cayne")
  line.gsub!("FREEMAN", "Freeman")
  line.gsub!("M Bessis", "Michel Bessis")
  line.gsub!("T Bessis", "Thomas Bessis")
  line.gsub!("SMIRNOV", "Smirnov")
  line.gsub!("PIEKAREK", "Piekarek")
  line.gsub!("HACKETT JU", "Justin Hackett")
  line.gsub!("HACKETT JA", "Jason Hackett")
  line.gsub!("JU HACKETT", "Justin Hackett")
  line.gsub!("JA HACKETT", "Jason Hackett")
  line.gsub!("LEE R\.", "Roger Lee")
  line.gsub!("Claudio Nunes C\.", "Claudio Nunes")
  line.gsub!("LALL J\.", "Justin Lall")
  line.gsub!("HELNESS", "Helness")
  line.gsub!("HELGEMO", "Helgemo")
  line.gsub!("J Lew Stansby", "Joanna Stansby")
  line.gsub!("L Lew Stansby", "Lew Stansby")
  line.gsub!("Brad MossOP", "Mossop")
  line.gsub!("Brad Mossop", "Mossop")

  line.gsub!(",morse", ",Morse")
  line.gsub!("FLEISHER", "Fleisher")
  line.gsub!("KAMIL", "Kamil")
  line.gsub!("BAKSHI", "Bakshi")
  line.gsub!("GITELMAN", "Fred Gitelman")
  line.gsub!("STANSBY", "Stansby")
  line.gsub!("MOSS", "Brad Moss")
  line.gsub!("NICKELL", "Nickell")
  line.gsub!("KATZ", "Katz")
  line.gsub!("Nickell Ni", "Nick Nickell")
  line.gsub!("Nick Nickellck", "Nick Nickell")
  line.gsub!("Nickell", "Nick Nickell")
  line.gsub!("Nick Nick Nickell", "Nick Nickell")
  line.gsub!("BESSIS", "Bessis")
  line.gsub!("Bessis M", "Michel Bessis")
  line.gsub!("Bessis T", "Thomas Bessis")
  line.gsub!("J\. LALL", "Justin Lall")
  line.gsub!("J\. Lall", "Justin Lall")
  line.gsub!("H\. LALL", "Hemant Lall")
  line.gsub!("H\. Lall", "Hemant Lall")
  line.gsub!("Platnick", "Brian Platnick")
  line.gsub!("Brian Brian Platnick", "Brian Platnick")
  line.gsub!("Fred Fred Gitelman", "Fred Gitelman")
  line.gsub!("Stansby", "Lew Stansby")
  line.gsub!("Lew Lew Stansby", "Lew Stansby")
  line.gsub!("T\. BESSIS", "Thomas Bessis")
  line.gsub!("T\. Bessis", "Thomas Bessis")
  line.gsub!("Nunes C\.", "Claudio Nunes")
  line.gsub!("Nunes Clau", "Claudio Nunes")
  line.gsub!("Nunes C", "Claudio Nunes")
  line.gsub!("NUNES", "Nunes")
  line.gsub!("Nunes", "Claudio Nunes")
  line.gsub!("FANTONI", "Fantoni")
  line.gsub!("Claudio Claudio Nunes", "Claudio Nunes")
  line.gsub!("Fantoni", "Fulvio Fantoni")
  line.gsub!("Fulvio Fulvio Fantoni", "Fulvio Fantoni")
  line.gsub!("Woolsey Kit", "Kit Woolsey")
  line.gsub!("Woolsey Ki", "Kit Woolsey")
  line.gsub!("Stewart Frank", "Frank Stewart")
  line.gsub!("Stewart Fr", "Frank Stewart")
  line.gsub!("T Helness", "Tor Helness")
  line.gsub!("Ja Hackett", "Jason Hackett")
  line.gsub!("Ju Hackett", "Justin Hackett")
  line.gsub!("D Bilde", "Dennis Bilde")
  line.gsub!("T\. Aa", "Terje Aa")
  line.gsub!("T\. Helness", "Tor Helness")
  line.gsub!("B\.Pollack", "Bill Pollack")
  line.gsub!("Defalco", "De Falco")
  line.gsub!("BILDE", "Bilde")
  line.gsub!("J\. Lall", "Justin Lall")
  line.gsub!("M\. Bessis", "Michel Bessis")
  line.gsub!("T\. Bessis", "Thomas Bessis")
  line.gsub!("MBessis", "Michel Bessis")
  line.gsub!("PGranovett", "Pamela Granovetter")
  line.gsub!("Ivatury", "Uday Ivatury")
  line.gsub!("Uday Uday Ivatury", "Uday Ivatury")
  line.gsub!("JWeinstein", "Jonathan Weinstein")
  line.gsub!("J\. Clerkin", "Jerry Clerkin")
  line.gsub!("M Bilde", "Morten Bilde")
  line.gsub!("A\. Sontag", "Alan Sontag")
  line.gsub!("WOLD", "Eddie Wold")

  line.gsub!("B Platnick", "Brian Platnick")
  line.gsub!("B\. Platnick", "Brian Platnick")
  line.gsub!("B\. Platnic", "Brian Platnick")
  line.gsub!("B\. Blancha", "Bob Blanchard")
  line.gsub!("S\. Blancha", "Shane Blanchard")
  line.gsub!("B\. Pollack", "Bill Pollack")
  line.gsub!("b\.pollack", "Bill Pollack")
  line.gsub!("Bathhurst", "Bathurst")
  line.gsub!("Berteau", "Bertheau")
  line.gsub!("D\. Clerkin", "Dennis Clerkin")
  line.gsub!("D\.clerkin", "Dennis Clerkin")
  line.gsub!("J\.clerkin", "Jerry Clerkin")
  line.gsub!("E\. Wold", "Eddie Wold")
  line.gsub!("Wold", "Eddie Wold")
  line.gsub!("Eddie Eddie Wold", "Eddie Wold")
  line.gsub!("F Nystrom", "F. Nystrom")
  line.gsub!("Gertsman", "Gerstman")
  line.gsub!("H Lall", "Hemant Lall")
  line.gsub!("H\. Lall", "Hemant Lall")
  line.gsub!("H\.lall", "Hemant Lall")
  line.gsub!("J\.lall", "Justin Lall")
  line.gsub!("Hweinstein", "Howie Weinstein")
  line.gsub!("John John Diamond", "John Diamond")
  line.gsub!("J John Diamond", "John Diamond")
  line.gsub!("J\. John Diamond", "John Diamond")
  line.gsub!("J Lall", "Justin Lall")
  line.gsub!("jlall", "Justin Lall")
  line.gsub!("J\. Wolpert", "Jenny Wolpert")
  line.gsub!("Kraynak", "Kranyak")
  line.gsub!("M\. Passell", "Mike Passell")
  line.gsub!("Passell", "Mike Passell")
  line.gsub!("Mike Mike Passell", "Mike Passell")
  line.gsub!("Mbessis", "Michel Bessis")
  line.gsub!("Nowosadski", "Nowosadzki")
  line.gsub!("Weischel", "Weichsel")

  line.gsub!("weinstein", "Weinstein")
  line.gsub!("levin", "Levin")

  line.gsub!("DIAMOND", "John Diamond")
  line.gsub!("Diamond", "John Diamond")
  line.gsub!("John Diamond Diamond", "John Diamond")
  line.gsub!("FALLENIUS", "Fallenius")
  line.gsub!("garner", "Garner")
  line.gsub!("Henner-Wel", "Henner-Welland")
  line.gsub!("Henner Wel", "Henner-Welland")
  line.gsub!("HWeinstein", "Howie Weinstein")
  line.gsub!("sWeinstein", "Steve Weinstein")
  line.gsub!("SWeinstein", "Steve Weinstein")
  line.gsub!("Versave", "Alfredo Versace")
  line.gsub!("Alfredo Versave A", "Alfredo Versace")
  line.gsub!("Alfredo Versace A", "Alfredo Versace")
  line.gsub!("Lanzarotti M", "Lanzarotti")
  line.gsub!("Uday,", "Uday Ivatury,")
  line.gsub!("BROGELAND", "Boye Brogeland")
  line.gsub!("Van Prooij,", "Van Prooijen,")
  line.gsub!("L\. Cohen", "Larry Cohen")
  line.gsub!("Clerkin D\.", "Dennis Clerkin")
  line.gsub!("Clerkin J\.", "Jerry Clerkin")
  line.gsub!("Clerkin D", "Dennis Clerkin")
  line.gsub!("Clerkin J", "Jerry Clerkin")
  line.gsub!("DClerkin", "Dennis Clerkin")
  line.gsub!("JClerkin", "Jerry Clerkin")
  line.gsub!("D Clerkin", "Dennis Clerkin")
  line.gsub!("J Clerkin", "Jerry Clerkin")
  line.gsub!("B\.Moss", "Brad Moss")
  line.gsub!("B\. Moss", "Brad Moss")
  line.gsub!("B Moss", "Brad Moss")
  line.gsub!("D\. Berkowi", "David Berkowitz")
  line.gsub!("Berkowitztz", "Berkowitz")
  line.gsub!("FFred Gitelm", "Fred Gitelman")
  line.gsub!("Gitelmanan", "Gitelman")
  line.gsub!("T\.Aa", "Aa")
  line.gsub!("H\. Lall", "Hemant Lall")
  line.gsub!("J\. Lall", "Justin Lall")
  line.gsub!("HLall", "Hemant Lall")
  line.gsub!("JLall", "Justin Lall")
  line.gsub!("TBessis", "Thomas Bessis")
  line.gsub!("MBessis", "MBessis")
  line.gsub!("M\.Bessis", "MBessis")
  line.gsub!("D Bilde", "Dennis Bilde")
  line.gsub!("M Bilde", "Morten Bilde")
  line.gsub!("DBilde", "Dennis Bilde")
  line.gsub!("MBilde", "Morten Bilde")
  line.gsub!("M\.Bilde", "Morten Bilde")
  line.gsub!("Hemant,", "Hemant Lall,")
  line.gsub!("DREWSKI", "Drew Casen")
  line.gsub!("JoeGrue", "Joe Grue")
  line.gsub!("Nowosadski", "Nowosadzki")
  line.gsub!("MGranovett", "Matthew Granovetter")
  line.gsub!("R\. Lee", "Roger Lee")
  line.gsub!("R\.Lee", "Roger Lee")
  line.gsub!("Woodridge", "Wooldridge")
  line.gsub!("Woolridge", "Wooldridge")
  line.gsub!("xiaodonp", "Xiaodong")
  line.gsub!("Zimmerman", "Zimmermann")
  line.gsub!("Zimmermannn", "Zimmermann")
  line.gsub!("DELMONTE", "Del'Monte")
  line.gsub!("del Monte", "Del'Monte")
  line.gsub!("Del Monte", "Del'Monte")
  line.gsub!("DelMonte", "Del'Monte")
  line.gsub!("Delmonte", "Del'Monte")
  line.gsub!("de Knijff", "De Knijff")

  line.gsub!("Auken J", "Jens Auken")
  line.gsub!("Auken S", "Sabine Auken")
  line.gsub!("A A Madala", "Agustin Madala")
  line.gsub!("Madala", "Agustin Madala")
  line.gsub!("Agustin Agustin Madala", "Agustin Madala")
  line.gsub!("A Greenberg", "Ari Greenberg")
  line.gsub!("A Greenber", "Ari Greenber")
  line.gsub!("A Gromov", "A Gromov")
  line.gsub!("A Grossack", "Adam Grossack")
  line.gsub!("A Kaplan", "Adam Kaplan")
  line.gsub!("A ZmudZinsk", "Adam Zmudzinski")
  line.gsub!("A Zmudzinski", "Adam Zmudzinski")
  line.gsub!("A Zmudzinsk", "Adam Zmudzinski")
  line.gsub!("A. Sementa", "Antonio Sementa")
  line.gsub!("A\.Kaplan", "Adam Kaplan")
  line.gsub!("A\.Zmudzins", "Adam Zmudzinski")
  line.gsub!("AA Terje", "Terje Aa")
  line.gsub!("AUKEN Sabi", "Sabine AUKEN")
  line.gsub!("Aa Terje", "Terje Aa")
  line.gsub!("Aa Therje", "Terje AA")
  line.gsub!("Bessis  M\.", "Michel Bessis")
  line.gsub!("Bessis  M", "Michel Bessis")
  line.gsub!("Bessis M\.", "Michel Bessis")
  line.gsub!("Bessis M", "Michel Bessis")
  line.gsub!("Bessis m", "Michel Bessis")
  line.gsub!("Bessis\. M", "Michel Bessis")
  line.gsub!("Bessis\.M", "Michel Bessis")
  line.gsub!("Bessis Mic", "Michel Bessis")
  line.gsub!("BessisM", "Michel Bessis")
  line.gsub!("BessisMich", "Michel Bessis")
  line.gsub!("Bessis_M", "Michel Bessis")
  line.gsub!("Bessis  T", "Thomas Bessis")
  line.gsub!("Bessis T\.", "Thomas Bessis")
  line.gsub!("Bessis Tho", "Thomas Bessis")
  line.gsub!("Bessis Th\.", "Thomas Bessis")
  line.gsub!("Bessis Th", "Thomas Bessis")
  line.gsub!("Bessis T", "Thomas Bessis")
  line.gsub!("Bessis. T", "Thomas Bessis")
  line.gsub!("Bessis.T", "Thomas Bessis")
  line.gsub!("BessisT", "Thomas Bessis")
  line.gsub!("BessisThom", "Thomas Bessis")
  line.gsub!("Bessis_T", "Thomas Bessis")
  line.gsub!("F.Fantoni", "Fulvio Fantoni")
  line.gsub!("Fantoni F", "Fulvio Fantoni")
  line.gsub!("Fantoni F.", "Fulvio Fantoni")
  line.gsub!("Fantoni G.", "Fulvio Fantoni")
  line.gsub!("Fantoni", "Fulvio Fantoni")
  line.gsub!("Fulvio Fulvio Fantoni", "Fulvio Fantoni")
  line.gsub!("Boye Boye Brogeland", "Boye Brogeland")
  line.gsub!("Eric Rodwell E", "Eric Rodwell")
  line.gsub!("EricGreco", "Eric Greco")
  line.gsub!("GRECO Eric", "Eric Greco")
  line.gsub!("Fisher Lot", "Lotan Fisher")
  line.gsub!("Fisher L", "Lotan Fisher")
  line.gsub!("Fisher.L", "Lotan Fisher")
  line.gsub!("H Weinstei", "Howie Weinstein")
  line.gsub!("Hacket.Ja", "Jason Hackett")
  line.gsub!("Hackett JA", "Jason Hackett")
  line.gsub!("Hackett Jason", "Jason Hackett")
  line.gsub!("Hackett Ja", "Jason Hackett")
  line.gsub!("Hackett-Ja", "Jason Hackett")
  line.gsub!("Hackett.Ja", "Jason Hackett")
  line.gsub!("HackettJas", "Jason Hackett")
  line.gsub!("Hacket\.Ju", "Justin Hackett")
  line.gsub!("Hackett Justin", "Justin Hackett")
  line.gsub!("Hackett Ju", "Justin Hackett")
  line.gsub!("Hackett-Ju", "Justin Hackett")
  line.gsub!("Hackett\.Ju", "Justin Hackett")
  line.gsub!("HackettJus", "Justin Hackett")
  line.gsub!("Hackett P\.", "Paul Hackett")
  line.gsub!("Hackett Pa", "Paul Hackett")
  line.gsub!("Hackett P", "Paul Hackett")
  line.gsub!("BERTENS Hu", "Huub Bertens")
  line.gsub!("BERTENS Huub", "Huub Bertens")
  line.gsub!("BESSIS Mic", "Michel Bessis")
  line.gsub!("BESSIS Tho", "Thomas Bessis")
  line.gsub!("BESSIS Thomas", "Thomas Bessis")
  line.gsub!("BESSIS mic", "Michel Bessis")

  line.gsub!("A Agustin Madala", "Agustin Madala")
  line.gsub!("A Sontag", "Alan Sontag")
  line.gsub!("A. Agustin Madala", "Agustin Madala")
  line.gsub!("A.Agustin Madala", "Agustin Madala")
  line.gsub!("Agustin Madala A A", "Agustin Madala")
  line.gsub!("Agustin Madala A D", "Agustin Madala")
  line.gsub!("Agustin Madala Ado", "Agustin Madala")
  line.gsub!("Agustin Madala Agu", "Agustin Madala")
  line.gsub!("Agustin Madala A\.", " Agustin Madala")
  line.gsub!("Agustin Madala A", "Agustin Madala")
  line.gsub!("BrogelandB", "Boye Brogeland")
  line.gsub!("BHamman", "Bob Hamman")
  line.gsub!("Bob Hamman B", "Bob Hamman")
  line.gsub!("Bob Hamman\. B", "Bob Hamman")
  line.gsub!("Hamman B", "Bob Hamman")
  line.gsub!("Hampson G.", "Geoff Hampson")
  line.gsub!("P Hackett", "Paul Hackett")
  line.gsub!("P Hamman", "Petra Hamman")
  line.gsub!("PetraHamman", "Petra Hamman")
  line.gsub!("Fisher L", "Lotan Fisher")
  line.gsub!("AFisher", "Arnie Fisher")
  line.gsub!("Ron Schwart", "Ron Schwartz")
  line.gsub!("Ron Schwartzz", "Ron Schwartz")
  line.gsub!("Graves", "Allan Graves")
  line.gsub!("Allan Allan Graves", "Allan Graves")
  line.gsub!("C\. Nunes", "Claudio Nunes")
  line.gsub!("C\.Nunes", "Claudio Nunes")
  line.gsub!("Nunes C\.", "Claudio Nunes")
  line.gsub!("Nunes\. C", "Claudio Nunes")
  line.gsub!("Nunes", "Claudio Nunes")
  line.gsub!("Claudio Claudio Nunes", "Claudio Nunes")
  line.gsub!("F.Fantoni", "Fulvio Fantoni")
  line.gsub!("Fulvio Fantoni\.", "Fulvio Fantoni")
  line.gsub!("Fulvio Fantoni", "Fulvio Fantoni")

  line.gsub!("Pepsi", "Pzszcola")
  line.gsub!("Pszczola", "Pzszcola")

  line.gsub!("S Weinstein", "Steve Weinstein")
	return line
end

# Given a list of LIN files, add the directory path.
ARGV.each do |file_name|

  data_file = File.read(file_name)

	out_file = file_name + ".tmp"
	File.open(out_file, 'w') { |output_file| 
		data_file.each_line do |line|

#			line.chomp!

			if (line.include? "pn|" ) then
				change_line(line)
			end

	  	output_file.write line
		end
	}

	safe_file = file_name + ".bck"
	FileUtils.mv(file_name, safe_file)
	FileUtils.mv(out_file, file_name)
end
